# This is a basic workflow to help you get started with Actions

name: Check if reviewd

on:
  schedule:
    - cron: "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - uses: yehudah/remind-the-reviewers@2ba984c9a12fd99326dc5b0ae609ded6e3966e58 
        with:
          # Remind every 3 hours
          interval: 3
