name: PHP Code Sniffer
on: pull_request
jobs:
  phpcs:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted        
        with:
          php-version: 7.2
          tools: composer, phpunit
          extensions: mbstring,PDO,grpc,tokenizer,xml,json,ctype,fileinfo,openssl,bcmath          
      - name: Install PHP Code Sniffer
        run: |
          mkdir ci
          cd ci
          git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
          git clone -b master https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          cd phpcs
          ./bin/phpcs --config-set installed_paths ../wpcs
      - name: Check coding standards
        run: wpcs/vendor/bin/phpcs
